[package]
name = "ste"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
lalrpop-util = "0.19.6"

[build-dependencies]
lalrpop = "0.19.6"
